name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}

main: ${mainClass}

commands:
    stock:
        description: CDStocks main command
        usage: /<command> [help|buy|sell]
